# Generated by Django 3.2.23 on 2025-02-12 04:38

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField()),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['state'], name='route_optim_state_4d32e7_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['retail_price'], name='route_optim_retail__f327d5_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=django.contrib.postgres.indexes.GistIndex(fields=['longitude', 'latitude'], name='route_optim_longitu_d3e130_gist'),
        ),
    ]
