# Generated by Django 3.2.23 on 2025-02-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
